name: Node CI 
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: My first step
        uses: docker://12.13.1-alpine3.9
    - run: npm install
    - run: npm run build
    - run: npm run test
